"""modelkedua

Revision ID: 0733700e14e5
Revises: 0c46122abbab
Create Date: 2017-07-15 14:32:26.793901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0733700e14e5'
down_revision = '0c46122abbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buku')
    # ### end Alembic commands ###
